# Generated by Django 4.0 on 2021-12-23 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20211130_0737'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
