# Generated by Django 4.0 on 2022-01-06 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('films', '0004_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_cien', models.CharField(max_length=150, verbose_name='Titulo')),
                ('direcion', models.CharField(max_length=150, verbose_name='Titulo')),
                ('estado', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='FilmUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vista', models.PositiveIntegerField(default=0)),
                ('estado', models.PositiveIntegerField(default=1)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
